title: Hem
resources:
  - url: /local/lovelace-card-tools/card-tools.js?v=1
    type: js
  - url: /local/lovelace-layout-card/layout-card.js?v=1
    type: js
  - url: /local/lovelace-list-card/list-card.js?v=1
    type: js
  - url: /local/lovelace-attribute-card/attribute-card.js?v=1
    type: js
  - url: /local/compact-custom-header/compact-custom-header.js?v=1
    type: module
views:
  - title: Översikt
    path: overview
    icon: mdi:home
    panel: true
    cards:
      - type: custom:layout-card
        cards:
          - type: weather-forecast
            entity: weather.smhi_home
            
          - type: entities
            title: 'Lampor'
            entities:
              - light.studio
              - light.couch_left
              - light.couch_right
              - light.kitchen_island
              - entity: switch.bed_lamp
                icon: mdi:lightbulb
              - entity: switch.wall_lamps
                icon: mdi:lightbulb
              - light.pendant_lamp
          
          - type: "custom:list-card"
            entity: sensor.todoist
            title: Inköpslista

          - type: custom:compact-custom-header
            main_config: true
            voice: clock
            clock_format: 24
   
  - title: Löpning
    path: running
    icon: mdi:run-fast
    panel: true
    cards:
      - type: custom:layout-card
        cards:
          - type: custom:compact-custom-header
    
  - title: TV/Film
    path: tv
    icon: mdi:television
    panel: true
    cards:
      - type: custom:layout-card
        cards:
          - type: custom:compact-custom-header
